Repository miit-projects/miit-guide-bot, pull requests merged in 2022-11, with the labels that each got.

#29 chore: add photos for `building_1`
  setup.py
  static/data.json
  static/images/building_1/0.jpg
  static/images/building_1/1.jpg
  static/images/building_1/2.jpg
  static/images/building_1/2.png
  static/images/building_1/3.jpeg
  static/images/building_1/4.jpg
Labels: Type: Enhancement, PR: Patch, Status: Ready

#31 feat: send multiple pictures in one message
  src/bot/_application.py
  src/bot/utils/media_adapters.py
Labels: Module: Core, Type: Enhancement, PR: Patch, Status: In progress

#34 fix: incorrect display of extra links
  src/bot/index.py
Labels: Module: Core, Type: Fix, PR: Patch, Status: Ready

#40 Release 1.1.0
  .gitignore
  src/bot/_application.py
  src/bot/constants/locations.py
  src/bot/entities/state_manager.py
  src/bot/index.py
  src/bot/types/location.py
  src/bot/types/state.py
  src/bot/utils/location.py
  src/bot/utils/media_adapters.py
  src/bot/utils/message.py
  tests/units/test_entities_state_manager.py
  tests/units/test_utils_location.py
Labels: Module: Core, Feature, Enhancement, Minor, In progress, Module: Logic, Infrastructure
