Repository miit-projects/miit-guide-bot, pull requests merged in 2022-10, with the labels that each got.

#2 feat(core module): add application core
  .gitignore
  README.md
  requirements.txt
  setup.py
  src/__init__.py
  src/__main__.py
  src/bot/__init__.py
  src/bot/_application.py
  src/bot/_config.py
  src/bot/_constants.py
  src/bot/index.py
  src/bot/utils/command_handler.py
Labels: Module: Core, Type: Feature, Type: Docs, PR: Major, Status: In progress

#3 feat(core module): add core module
  .gitignore
  README.md
  requirements.txt
  setup.py
  src/__init__.py
  src/__main__.py
  src/bot/__init__.py
  src/bot/_application.py
  src/bot/_config.py
  src/bot/_constants.py
  src/bot/index.py
  src/bot/utils/command_handler.py
Labels: Module: Core, Type: Feature, Type: Docs, PR: Major, Status: Need review

#5 feat(send_photo): add `send_photo` feature to the core module
  src/bot/_application.py
  src/bot/index.py
Labels: Module: Core, Type: Feature, PR: Patch, Status: In progress

#7 feat(auto-setup): add auto-setup script for development
  auto-setup.bat
Labels: Type: Enhancement, PR: Patch, Status: In progress

#6 feat(bot-user-cooperation): setup main bot loop logic
  src/bot/_application.py
  src/bot/_constants.py
  src/bot/constants/config.py
  src/bot/constants/locations.py
  src/bot/constants/replies.py
  src/bot/env.py
  src/bot/index.py
  src/bot/types/buttons.py
  src/bot/types/external.py
  src/bot/types/location.py
  src/bot/types/message.py
  src/bot/utils/command_handler.py
  src/bot/utils/config.py
  src/bot/utils/keyboard.py
  src/bot/utils/location.py
  src/bot/utils/state_manager.py
Labels: Type: Feature, Type: Fix, Type: Enhancement, PR: Minor, Module: Logic, Status: Ready

#14 chore: refactoring
  src/bot/constants/locations.py
  src/bot/entities/database.py
  src/bot/entities/state_manager.py
  src/bot/index.py
  src/bot/types/location.py
  src/bot/utils/location.py
  tests/units/test_entities_database.py
  tests/units/test_entities_state_manager.py
  tests/units/test_utils_location.py
Labels: Type: Fix, Type: Enhancement, PR: Patch, Module: Logic, Status: Need review

#16 chore: improve state manager system
  src/bot/constants/locations.py
  src/bot/constants/state.py
  src/bot/entities/state_manager.py
  src/bot/types/location.py
  src/bot/types/state.py
  src/bot/utils/location.py
  tests/units/test_entities_state_manager.py
Labels: Module: Core, Type: Fix, Type: Enhancement, PR: Patch, Status: In progress

#19 fix: main logic file, sync it with the updated state manager
  src/bot/index.py
Labels: Type: Enhancement, PR: Patch, Module: Logic, Status: Ready

#12 feat(data-transfer): add data-transfer model to improve data control
  auto-setup.bat
  run-tests.bat
  src/bot/_application.py
  src/bot/constants/keyboard.py
  src/bot/constants/locations.py
  src/bot/constants/replies.py
  src/bot/constants/state.py
  src/bot/entities/database.py
  src/bot/entities/state_manager.py
  src/bot/index.py
  src/bot/types/buttons.py
  src/bot/types/external.py
  src/bot/types/location.py
  src/bot/types/state.py
  src/bot/utils/database.py
  src/bot/utils/keyboard.py
  src/bot/utils/location.py
  src/bot/utils/state_manager.py
  static/data.json
  static/images/building_1/1.jpg
  static/images/building_1/2.jpg
  static/images/street/1.jpg
  static/images/street/2.jpg
  tests/units/test_constants_location.py
  tests/units/test_entities_database.py
  tests/units/test_entities_state_manager.py
  tests/units/test_types_external.py
  tests/units/test_utils_database.py
  tests/units/test_utils_keyboard.py
  tests/units/test_utils_location.py
Labels: Module: Core, Type: Feature, Type: Fix, Type: Enhancement, PR: Minor

#22 chore: add icons to empty menu buttons
  src/bot/types/buttons.py
Labels: Type: Enhancement, PR: Patch, Module: Logic, Status: Need review

#23 chore: add icons to empty menu buttons (#22)
  src/bot/types/buttons.py
Labels: Type: Enhancement, PR: Patch, Module: Logic, Status: Need review

#24 feat(lnfo): add information about locations and links to external sources of information
  src/bot/_application.py
  src/bot/constants/replies.py
  src/bot/index.py
  static/data.json
Labels: Type: Feature, Type: Enhancement, PR: Patch, Module: Logic, Status: Need review

#26 chore: add external links
  static/data.json
Labels: Type: Enhancement, PR: Patch, Module: Logic, Status: Need review

#27 chore: global update of assets
  README.md
  auto-setup.bat
  requirements.txt
  requirements_dev.txt
  run-tests.bat
  scripts/run-tests.bat
  scripts/setup-dev.bat
  scripts/setup-prod.bat
  static/data.json
  static/images/street/0.jpg
  static/images/street/2.jpg
  static/images/street/3.jpg
  static/images/street/5.jpg
  static/images/street/6.webp
Labels: Module: Core, Type: Feature, Type: Fix, Type: Enhancement, PR: Minor, Module: Logic, Status: Ready
